---
title: "ProjektKK"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ProjektKK}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = T,
  message = F,
  warning = F
)
```

```{r setup}
library(ProjektKK)
getwd()
```

***

**Kacper Krasicki**

**AGH** 
Akademia Górniczo - Hutnicza im. Stanisława Staszica w Krakowie
Wydzia Geodezji Górniczej i Inżynierii Środowiska
Kierunek - Geoinformacja

**E-mail** kkrasicki98@gmail.com


#Instalacja pakietu

```{r}
# devtools, sprawdzamy czy jest, jeśli nie to instalujemy i wczytujemy
if(!require(devtools)) {install.packages("devtools"); require(devtools)}
# instalcja pakietu gios_import
devtools::install_github("K4krasin/ProjektKK")
library(ProjektKK)
```


Biblioteki które moga byc potrzebne do tego pakietu.

```{r}
library(dplyr)
library(ggplot2)
library(openxlsx)
library(tidyverse)
```

Funkcja 1 

```{r}
load_all()
Funkcja1() -> nowy
    nowy %>% glimpse()

 nowy %>%
   group_by(Segment) %>%
   summarise(emis = sum(Emisja))

```

Funkcja 2

```{r}
Funkcja2()
```

